### ISSUE TITLE
eror form no tanah bangunan

### ISSUE THREAD

**Issue by senthaku** [akhwan90/sisko#1]
mas di form input inventaris selain gedung dan tanah, di pengisian menu letak tidak bisa pilih ruangnya, ditunggu pencerahannya 
menu pilih ruang input barang non gedung dan tanah.

A PHP Error was encountered

Severity: Notice
Message: Undefined variable: ruang
Filename: adm/f_no_tanah_bgn.php
Line Number: 76

A PHP Error was encountered

Severity: Warning
Message: Invalid argument supplied for foreach()
Filename: adm/f_no_tanah_bgn.php
Line Number: 76

**Comment by akhwan90** [comment]
sudah update gan 
https://github.com/akhwan90/sisko/commit/86b475ff21ef16110f2c1951efb2314b17f0834d
